[project]
name = "clarity-template"
requirements = []

[contracts.base]
path = "contracts/base.clar"
depends_on = []


# EXTERNAL CONTRACTS
[contracts.sip-010-trait-ft-standard]
path = "contracts/external/sip-010-trait-ft-standard.clar"
depends_on = []
